version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "my-rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "ssafy"
      RABBITMQ_DEFAULT_PASS: "ssafy"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    restart: always

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
    restart: always

volumes:
  rabbitmq_data:
  mongodb_data: