server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/togeball_chat_2
  rabbitmq:
    host: localhost
    port: 5672
    username: ssafy
    password: ssafy
  cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static: ap-northeast-2
      s3:
        bucket: togeball-bucket
  servlet:
    multipart:
      max-file-size: 100MB

logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG
    io:
      awspring:
        cloud: DEBUG

rabbitmq:
  exchange:
    name: togeball.chat.exchange
  queue:
    name: togeball.chat.queue
