server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/togeball_chat
  rabbitmq:
    host: localhost
    port: 5672
    username: ssafy
    password: ssafy


logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG